"""
Automation Schemas — Data contracts for desktop actions, observations, and goals.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class ActionType(str, Enum):
    """Supported desktop automation action primitives."""
    # Mouse actions
    CLICK = "click"
    DOUBLE_CLICK = "double_click"
    RIGHT_CLICK = "right_click"
    DRAG = "drag"
    SCROLL = "scroll"
    MOVE = "move"

    # Keyboard actions
    TYPE = "type"
    PRESS_HOTKEY = "press_hotkey"
    PRESS_KEY = "press_key"

    # UIA / Application actions
    INVOKE_ELEMENT = "invoke_element"
    LAUNCH_APP = "launch_app"
    CLOSE_WINDOW = "close_window"
    FOCUS_WINDOW = "focus_window"
    SNAP_WINDOW = "snap_window"

    # Media & System
    SET_VOLUME = "set_volume"
    MEDIA_KEY = "media_key"
    TOAST_NOTIFICATION = "toast_notification"

    # Control flow
    WAIT = "wait"
    DONE = "done"
    FAIL = "fail"


class UIElementInfo(BaseModel):
    """Extracted UI element information from Windows UI Automation."""
    id: int
    name: str = ""
    control_type: str = ""
    automation_id: str = ""
    class_name: str = ""
    bounding_box: tuple[int, int, int, int] = (0, 0, 0, 0)  # (left, top, width, height)
    center_point: tuple[int, int] = (0, 0)                  # (x, y)
    is_enabled: bool = True
    is_keyboard_focusable: bool = False
    value: str = ""


class WindowInfo(BaseModel):
    """Metadata of an active or background desktop window."""
    handle: int
    title: str
    class_name: str = ""
    process_id: int = 0
    process_name: str = ""
    is_active: bool = False
    rect: tuple[int, int, int, int] = (0, 0, 0, 0)  # (left, top, right, bottom)
    width: int = 0
    height: int = 0


class AutomationObservation(BaseModel):
    """Environment observation captured before or after an action."""
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())
    active_window: WindowInfo | None = None
    open_windows: list[WindowInfo] = Field(default_factory=list)
    uia_elements: list[UIElementInfo] = Field(default_factory=list)
    screenshot_path: str | None = None
    screen_resolution: tuple[int, int] = (1920, 1080)
    cursor_position: tuple[int, int] = (0, 0)


class AutomationAction(BaseModel):
    """A discrete action command generated by the automation agent."""
    action_type: ActionType
    element_id: int | None = None
    coordinates: tuple[int, int] | None = None
    text: str | None = None
    keys: list[str] | None = None
    direction: str | None = None          # For scroll: "up" | "down"
    amount: int | float | None = None     # For scroll clicks, volume percent, wait seconds
    target: str | None = None             # App name, window title, or snap direction
    reason: str = ""                      # CoT justification for why this action was chosen


class AutomationStep(BaseModel):
    """A single perception-action-verification step in an autonomous workflow."""
    step_number: int
    observation_summary: str = ""
    action: AutomationAction
    action_result: str = ""
    success: bool = True
    duration_seconds: float = 0.0
    screenshot_before: str | None = None
    screenshot_after: str | None = None


class AutomationGoalStatus(str, Enum):
    """Current lifecycle status of an autonomous task."""
    PENDING = "pending"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"
    ABORTED = "aborted"


class AutomationGoal(BaseModel):
    """An end-to-end user goal with execution trace and status."""
    goal_id: str
    goal: str
    status: AutomationGoalStatus = AutomationGoalStatus.PENDING
    max_steps: int = 30
    current_step: int = 0
    steps: list[AutomationStep] = Field(default_factory=list)
    created_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    completed_at: str | None = None
    final_output: str = ""
    error_message: str | None = None
